#!/usr/bin/env node
/* Repo: https://github.com/jneidel/signal-cli-to-file */
const fs = require('node:fs/promises');
const path = require("path");
const { createProcessor } = require("./src/processor");

// In signal-cli registered number you want to receive messages for
const signalNumber = "";
// for example:
// const signalNumber = "+4917222222222";

// The directory where messages are to be created as files
const inboxDir = "";
// for example:
// const inboxDir = path.join(process.env.HOME, "org/inbox");

// The host + port where the signal-cli-rest-api service is running
const apiHost = "";
// for example:
// const apiHost = "http://192.168.178.23:8080";

// Default message file extension
const messageFileExtension = "md";

// Turn on to enable debugging output
const debugging = false;

// Turn off to disable messages being backed-up in $XDG_CACHE_HOME
const backupMessages = true;

// Turn on to not delete the attachments on the server after downloading them
const keepAllAttachments = false;

// Add the numbers of senders and groups you want to receive messages from
// If array is non-empty, all messages not from senders or groups in the list will be ignored
// Format: [ "+49172171717", "nDfe1bpw9GDAm68w/i3VENs6JWqoTtBYm42DY5o3ShY=" ]
const senderAndGroupWhitelist = [];

const filenameFromBodyCutoff = 60;
const filenameFromTitleCutoff = 80;

if (!signalNumber || !inboxDir || !apiHost) {
    console.error("The required configuration variables are not set.")
    process.exit(1);
}
fs.stat(inboxDir).catch(() => {
    console.error( `Configured inboxDir '${inboxDir}' does not exist` )
    process.exit(2);
})
fetch(`${apiHost}/v1/health`).catch(() => {
    console.error( `Configured apiHost '${apiHost}' is not reachable` )
    process.exit(3);
})

const processor = createProcessor({
    inboxDir,
    apiHost,
    messageFileExtension,
    debugging,
    backupMessages,
    keepAllAttachments,
    senderAndGroupWhitelist,
    filenameFromBodyCutoff,
    filenameFromTitleCutoff
});
const { logError, processMessages } = processor;

fetch(`${apiHost}/v1/receive/${signalNumber}?ignore_stories=true&send_read_receipts=true`)
    .then( r => r.json() )
    .then( messages => {
        if (debugging) console.log( "Results from /receive:\n" + JSON.stringify(messages, null, 2) )

        if ( messages?.error )
            logError(`Error on /receive:
${messages.error}`).then(() => process.exit(1))

        processMessages(messages);
    })
